from .backlist_token import *
from .storage import *
from .user import * 
from .address import *
from .hopitals import *
from .service_hopitals import *
from .titres import *
from .specialite import *
from .consultants import *
from .sexe import *
from .religion import *
from .patients import *
from .rendez_vous import *
from .consultants import *
from .rendez_vous import *